// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using again.Models;

namespace again.Migrations
{
    [DbContext(typeof(againContext))]
    [Migration("20180831180444_eventmodeldbset2")]
    partial class eventmodeldbset2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("again.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("EventTitle");

                    b.Property<string>("Notes");

                    b.HasKey("EventID");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("again.Models.EventGames", b =>
                {
                    b.Property<int>("EventGamesID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventID");

                    b.Property<int>("GameID");

                    b.HasKey("EventGamesID");

                    b.HasIndex("EventID");

                    b.HasIndex("GameID");

                    b.ToTable("EventGames");
                });

            modelBuilder.Entity("again.Models.EventPlayers", b =>
                {
                    b.Property<int>("EventPlayersID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventID");

                    b.Property<int>("PlayerID");

                    b.HasKey("EventPlayersID");

                    b.HasIndex("EventID");

                    b.HasIndex("PlayerID");

                    b.ToTable("EventPlayers");
                });

            modelBuilder.Entity("again.Models.Game", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("EventID");

                    b.Property<string>("ImgPath");

                    b.Property<int>("MaxPlayer");

                    b.Property<int>("MinPlayer");

                    b.Property<int?>("PlayerID");

                    b.Property<string>("ThumbPath");

                    b.Property<string>("Title");

                    b.HasKey("GameID");

                    b.HasIndex("EventID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("again.Models.Library", b =>
                {
                    b.Property<int>("LibraryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameID");

                    b.Property<int>("PlayerID");

                    b.HasKey("LibraryID");

                    b.HasIndex("GameID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Library");
                });

            modelBuilder.Entity("again.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EventID");

                    b.Property<string>("Name");

                    b.HasKey("PlayerID");

                    b.HasIndex("EventID");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("again.Models.EventGames", b =>
                {
                    b.HasOne("again.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("again.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("again.Models.EventPlayers", b =>
                {
                    b.HasOne("again.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("again.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("again.Models.Game", b =>
                {
                    b.HasOne("again.Models.Event")
                        .WithMany("EventGames")
                        .HasForeignKey("EventID");

                    b.HasOne("again.Models.Player")
                        .WithMany("Games")
                        .HasForeignKey("PlayerID");
                });

            modelBuilder.Entity("again.Models.Library", b =>
                {
                    b.HasOne("again.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("again.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("again.Models.Player", b =>
                {
                    b.HasOne("again.Models.Event")
                        .WithMany("EventPlayers")
                        .HasForeignKey("EventID");
                });
#pragma warning restore 612, 618
        }
    }
}
